
1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def DivideByZero(x,y):
    try:
        x/y
    except ZeroDivisionError as e:
        print("An execption has been occured as, ",e, " ,action has been attempted")

x,y=5,0

DivideByZero(x,y)

An execption has been occured as,  division by zero  ,action has been attempted


2. Implement a Python program to generate all sentences where subject is in
["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in
["Baseball","cricket"].


Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]



Output should come as below:
    
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [2]:
subject=["Americans","Indians"]
verb=["play","watch"]
objects=["Baseball","Cricket"]

Syntax = [(sub+' '+vrb+' '+objecct+".") for sub in subject for vrb in verb for objecct in objects]

print("Output:")

for syn in Syntax:    
    print(syn)

Output:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


3. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [4]:
import numpy as np
x = np.array([1,2,3,4,5])
N=5
matrix1 = np.vander(x,N,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [5]:
np.linalg.det(matrix)

287.99999999999517

In [6]:
np.linalg.det(matrix1)

287.99999999999517